name: Runtime-risks
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Installing Prerequisites (Kind Cluster)
        uses: helm/kind-action@v1.4.0
        run: |
          kubectl cluster-info --context kind-chart-testing
          kubectl wait --for=condition=Ready nodes --all --timeout=120s  

      - name: Install karmor, kubearmor and discovery engine
        run: |
          curl -sfL http://get.kubearmor.io/ | sudo sh -s -- -b /usr/local/bin
          karmor version
          karmor install
          kubectl apply -f https://raw.githubusercontent.com/kubearmor/discovery-engine/dev/deployments/k8s/deployment.yaml
          kubectl wait --for=condition=Ready pods --all -n accuknox-agents --timeout=120s

      - name: Run e2e tests
        uses: kubearmor/kubearmor@main
        run: |
          cd tests
          make

#      - name: Deploy test application
#        run: |
#          kubectl create deployment nginx --image=nginx
#          POD=$(kubectl get pod -l app=nginx -o name)

      - name: Generate report
        run: |
          karmor summary --agg -o json > /tmp/summary.json

#      - name: Compare baseline report
#        run: |
#          git diff /tmp/baseline.json /tmp/summary.json --histogram

