name: Runtime-risks
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: debianmaster/actions-k3s@master
        id: k3s
        with:
          version: 'latest'

      - run: |
          kubectl get nodes
          kubectl get pods -A
          sleep 20
          kubectl get pods -A

      - name: Configuring and testing the Installation for cluster
        run: |
          sudo apt-get install -y socat
          kubectl wait --for=condition=Ready nodes --all --timeout=120s
      #          kubectl cluster-info --context kind-chart-testing

      - name: Install karmor, kubearmor and discovery engine
        run: |
          curl -sfL http://get.kubearmor.io/ | sudo sh -s -- -b /usr/local/bin
          karmor version
          karmor install
          kubectl apply -f https://raw.githubusercontent.com/kubearmor/discovery-engine/dev/deployments/k8s/deployment.yaml
          sleep 5s
          kubectl wait --for=condition=Ready pods --all -n accuknox-agents --timeout=120s

      - name: Checkout Kubearmor repo
        uses: actions/checkout@v3
        with:
          repository: kubearmor/kubearmor
          path: kubearmor

#      - name: Run e2e tests
#        run: |
#          ls
#          cd kubearmor/tests
#          go install -mod=mod github.com/onsi/ginkgo/ginkgo
#          make test

#      - name: Deploy test application
#        run: |
#          kubectl create deployment nginx --image=nginx
#          POD=$(kubectl get pod -l app=nginx -o name)

      - name: Generate report
        run: |
          kubectl wait --for=condition=Ready pods --all -A --timeout=120s
          sleep 100s
          kubectl get pods -A
          karmor summary
#          kubectl logs -f $(kubectl get pods -l kubearmor-app=kubearmor-relay -A -o jsonpath='{.items[0].metadata.name}') -n kubesystem | tail
#          kubectl logs -f $(kubectl get pods -l app=discovery-engine -A -o jsonpath='{.items[0].metadata.name}') -n accuknox-agents

#      - name: Compare baseline report
#        run: |
#          git diff /tmp/baseline.json /tmp/summary.json --histogram

